// PLEASE USE YOUR OWN MAPBOX API KEY. API KEY IS FOR DEMO PURPOSES ONLY.
window.MAPBOX_CRED =
  "pk.eyJ1IjoibWFudWVsYmFuemEiLCJhIjoiY2syYzA0NGV0MDcxcTNjbGNlODY4NDR1ZyJ9.SUXHI1TRqNXKr3uPFzgNjQ";

// PLEASE USE YOUR OWN API KEY. API KEY IS FOR DEMO PURPOSES ONLY. https://shademap.app/about
window.SHADEMAP_CRED =
  "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hbnVlbGJhbnphQGhvdG1haWwuY29tIiwiY3JlYXRlZCI6MTY4OTAxNjI3MzU3OSwiaWF0IjoxNjg5MDE2MjczfQ.BHqt9Njn5a9-q7d3b0gYhU9Bn4Z305zh3hwYCan-HhM";
